### ISSUE TITLE
Maybe placeholders for two cameras if we have spare pins?

### ISSUE THREAD

**Issue by goran-mahovlic** [emard/ulx3s#1]
For experiments with computer vision ...
http://www.voti.nl/docs/OV7670.pdf
http://www.electrodragon.com/w/OV7670_Module

**Comment by emard** [comment]
Pin count will be tight as this BGA-381 has many pins used as GND and VCC
So some pins might be shared with something else

Let's list some more wishes for placeholders
IR camera
SPI OLED display
LORA module
RTC

**Comment by emard** [comment]
SPI OLED display, RTC and ESP-32 made it.
IR camera and LORA haven't.
Useful pin count is low, though there are still some free pins
in the inner circle of BGA but most of them are unrouteable
using 5/5 mil process. Going to 4/4 mils PCB will be too expensive.
