### ISSUE TITLE
Kitspace Digikey/Mouser links still an issue?

### ISSUE THREAD

**Issue by kasbah** [emard/ulx3s#10]
Hey, I was just re-reading the readme. I noticed this section:

> Parts can be ordered from Detailed BOM or from ULX3S at Kitspace, which automatically submits Simplified 1-click BOM by clicking on "Digikey" or "Mouser" button. On each click, Digikey and Mouser will keep accumulating the BOM in the shopping cart. Number of unique parts on Digikey and Mouser should be equal but Digikey scripts have bugs. First time click on "Digikey" will upload a partial BOM, then the shopping cart must be reset and next click on "Digikey" will upload complete BOM. To reset shopping cart, click "New Cart" or "New Basket". Kitspace may be updated with about 1 day delay after this project update.

Can you confirm that Digikey links still have this issue?

**Comment by emard** [comment]
No, I updated readme.

**Comment by kasbah** [comment]
Thanks!
