### ISSUE TITLE
Wrong SDRAM part number in schematic for version 3.17

### ISSUE THREAD

**Issue by mahesh-electronut** [emard/ulx3s#17]
As per `schematics_v317.pdf`, SDRAM part number is **MT48LC16M16A2TG**. But the part populated on the v317 board is **IS42S16160G-7TL**. Please update the schematic PDF.

**Comment by goran-mahovlic** [comment]
Hi @mahesh-electronut there are different production runs on different versions of ULX3S - parts we placing in production are really depending on whet is available on market. So as for schematics - both pats are fitting this board, and I think it would be hard for emard to write all possible SDRAM chip that would be compatible with this board.

But there is a list with a list of SDRAM version here:

https://github.com/emard/ulx3s/blob/master/doc/MANUAL.md#board-versions

**Comment by mahesh-electronut** [comment]
Thanks for the quick reply @goran-mahovlic . That sounds fine. 

Just one more clarification I needed:

IS42S16160G shows pins DQ0 to DQ07 whereas MT48LC16M16A2TG has D0 to D15. I found an SDRAM controller for MT48LC16M16A2TG , but I am wondering if it will work for IS42S16160G because of this difference. Thanks for any input on this.

**Comment by mahesh-electronut** [comment]
> IS42S16160G shows pins DQ0 to DQ07 whereas MT48LC16M16A2TG has D0 to D15. I

Sorry, was looking at wrong part in datasheet. Closing, thanks!
