### ISSUE TITLE
Schematics for 3.1.8 from Mouser?

### ISSUE THREAD

**Issue by fsctl** [emard/ulx3s#20]
Hi emard,

I ❤️ the ULX3S, but one I [bought from Mouser last week](https://www.mouser.com/ProductDetail/392-CS-ULX3S-03) is giving me trouble and I cannot find schematics for it.  

The board has silkscreen on the back that says `3.1.8`.  But the latest Kicad file in this repo is only `3.1.7`.  Where can I get the schematics for board `3.1.8`?

![ulx3s-3 1 8](https://github.com/emard/ulx3s/assets/104329282/7f85dc3d-ef6f-4407-9ac7-710c3db650cd)

The specific problem I'm trying to debug is that the ESP32 is not recognized by `esptool.py` or any other tool, and I suspect that's because the ESP32-WROVER-E's `EN` pin is only at 1.7V.  The board has been a bit flaky in other ways too.  Would be much easier to debug with the schematic.

By the way, output of `ftx_prog` in factory configuration shows board at version `3.0.8`.  I assume I should change this to `3.1.8`?

<img width="394" alt="ftx_prog" src="https://github.com/emard/ulx3s/assets/104329282/87a84655-bb3b-420d-87dd-e0de233e02b0">

Thank you!

**Comment by goran-mahovlic** [comment]
Hi, 
v3.1.8 is on my repository. Nothing special is changed just number of layers and logos.
So schematics from v3.1.7 is still ok for checking.

You can contact me at goran.mahovlic@gmail.com or on discord it will be easier to trace a problem 

https://discord.com/invite/8pgjZqG9Ur

Here is repository for 6 layer board.

https://github.com/ulx3s/ulx3s

And I can already see that something happened with that board - I see C49 is missing - can you send me both side quality picture so I can check what else looks suspicious.

All boards are tested by production company D&M but maybe they missed something.
In any way if something is wrong with this one we can exchange it for a new one!

Also board have USB DFU firmware so if you want to update bitstream in flash you will need to power up the board with holding BTN1 and BTN2 (most left buttons on the board).

Goran

**Comment by emard** [comment]
If you like, you can rename the board to 3.1.8
in the manual it is described how to do it using
opensource ftx_prog on linux and name it back
if needed. I'm not shure how many reflashings
of this are allowed, but for few changes it should
be fine

fujprog needs to be recompiled to accept
new version, that's why we are reluctant to
give the board latest versions. openFPGAloader
and others doesn't care about version.

**Comment by goran-mahovlic** [comment]
Yes few renamings should be fine. We have tested 4 and it still holds. Originaly boards are flashed just once. 
As fujprog is bit slow in keeping up we are just flashing all with v3.0.8 But serial is unique and I will check in testing database if I can find something that was at least double tested on your board. Sometimes even when you have dfu with passtrue loaded it is still hard to get esp in flash mode. I see that new esptool claim it is bit better so you can try with that one.

**Comment by fsctl** [comment]
Thanks, @goran-mahovlic.  I think I was using the `*_v20_*` version of the constraints file when I flashed (since `ftx_prog` was originally reporting it as a v3.0.8 board and I assumed it was; didn't see the silkscreen until later), and maybe that was pulling ESP32's `EN` low by competing with the hardwired pull up on that pin.  I'll investigate it more this weekend and reach out on email or discord if I'm still having problems.  Closing this issue now as you have answered my question -- thanks!

**Comment by goran-mahovlic** [comment]
> Thanks, @goran-mahovlic. I think I was using the `*_v20_*` version of the constraints file when I flashed (since `ftx_prog` was originally reporting it as a v3.0.8 board and I assumed it was; didn't see the silkscreen until later), and maybe that was pulling ESP32's `EN` low by competing with the hardwired pull up on that pin. I'll investigate it more this weekend and reach out on email or discord if I'm still having problems. Closing this issue now as you have answered my question -- thanks!

Thank you! And remember for accesing esp32 over serial you always need to have passthru or create your own. 

I think latest source for pass is here

https://github.com/emard/ulx3s-misc/tree/master/examples/esp32_passthru/proj

And bitstream here: https://github.com/emard/ulx3s-bin/tree/master/fpga/dfu/85f-v317
