### ISSUE TITLE
schematics pdf is not searchable

### ISSUE THREAD

**Issue by dpavlin** [emard/ulx3s#7]
It seems that schematics pdf is not searchable, which is shame, since finding components is much easier using search. Just re-creating schematics from current version of KiCad wil fix it. Tested with KiCad 5.0.2+dfsg1-1 on Debian sid.

This will also create color pdf with correct orientation, so win, win :-)

**Comment by emard** [comment]
J1/J2 mirrored to look the same as on PCB.
Schematics exported from "Plot" menu is now searchable.

Before I was exported it from "Print" menu and that was
the main reason of unsearchability.

**Comment by gojimmypi** [comment]
this is a great change! and thanks for orienting the schematic to be readable in landscape mode, too :)
